---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      name: container2-pods
      labels:
        app: container2
    spec:
      containers:
        - name: container2-node
          image: us-east1-docker.pkg.dev/csci5409kubernetes/kubernetesa3artifactrepo/assignment-3
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: container-volume
              mountPath: "/sarthak_PV_dir"
      volumes:
        - name: container-volume
          persistentVolumeClaim:
            claimName: sarthak-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: LoadBalancer
  selector:
    app: container2
  ports:
    - port: 80
      targetPort: 3000
