# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: sarthak-pv
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /sarthak_PV_dir
#     type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sarthak-pvc
# spec:
#   volumeName: sarthak-pv
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sarthak-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

